# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23d5265fcc83c351fb0ace076ef1089102481b343718742db15f34e837b383cfeab8928a8115090c4522d248751c7ba480a5e6e59f5a7d682d88c94e68ac4e52

test:
  secret_key_base: 7525b26ae2e003ee29c2aadd80ae538fdc4ad330bea525e6aa1d2d99efe4cec50e7e35467ceb0c1d5b477cdac90e2655a91b9421a0d82baa4acade595671b882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
